#!/usr/bin/env python3
# Tello Drone Coverage Path Code
# Generated by Wings of Discovery

import time
from djitellopy import Tello

def execute_coverage_path():
    """Execute the coverage path for archaeological survey"""
    # Initialize Tello
    drone = Tello()
    drone.connect()
    
    # Check battery
    battery = drone.get_battery()
    print(f"Battery level: {battery}%")
    if battery < 20:
        print("Warning: Battery level is low!")
        return

    # Takeoff
    print("Taking off...")
    drone.takeoff()
    time.sleep(2)

    # Execute coverage path
    path_lines = [
        {"dx": 0, "dy": 23},
        {"dx": 0, "dy": 23},
        {"dx": 0, "dy": 23},
        {"dx": 0, "dy": 23}
    ]

    # Fly along each sector line and take photos
    print("Starting coverage path...")
    photo_count = 0
    
    for i, line in enumerate(path_lines):
        print(f"Segment {i+1}/{len(path_lines)}")
        
        # Move forward
        if abs(line["dx"]) > 0:
            if line["dx"] > 0:
                drone.move_forward(int(abs(line["dx"])))
            else:
                drone.move_back(int(abs(line["dx"])))
        
        if abs(line["dy"]) > 0:
            if line["dy"] > 0:
                drone.move_right(int(abs(line["dy"])))
            else:
                drone.move_left(int(abs(line["dy"])))
        
        # Take photo
        frame = drone.get_frame_read().frame
        if frame is not None:
            import cv2
            cv2.imwrite(f"photo_{photo_count:04d}.jpg", frame)
            photo_count += 1
            print(f"  Photo {photo_count} saved")
        
        time.sleep(0.5)  # Wait 0.5 seconds

    print(f"\nTotal photos taken: {photo_count}")

    # Land
    print("Landing...")
    drone.land()
    print("Mission complete!")

if __name__ == "__main__":
    execute_coverage_path()
