#!/usr/bin/env python3
"""
Tello Drone Image Extraction Script
Downloads all photos from the Tello drone to local storage
Generated by Wings of Discovery
"""

import os
import time
from datetime import datetime
from djitellopy import Tello

def create_image_directory():
    """Create a timestamped directory for storing images"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    dir_name = f"tello_images_{timestamp}"
    
    if not os.path.exists(dir_name):
        os.makedirs(dir_name)
    
    print(f"Created directory: {dir_name}")
    return dir_name

def download_images_from_tello():
    """Connect to Tello and download all images"""
    print("Connecting to Tello drone...")
    
    try:
        # Initialize Tello
        tello = Tello()
        tello.connect()
        
        # Get battery level
        battery = tello.get_battery()
        print(f"Battery level: {battery}%")
        
        if battery < 10:
            print("Warning: Battery level is low!")
        
        # Create directory for images
        image_dir = create_image_directory()
        
        # Initialize video stream to access photos
        tello.streamon()
        time.sleep(2)  # Wait for stream to initialize
        
        print("Downloading images from drone...")
        
        # Get frames and save as images
        frame_count = 0
        max_frames = 100  # Limit number of frames to capture
        
        for i in range(max_frames):
            frame = tello.get_frame_read().frame
            
            if frame is not None:
                # Save frame as image
                filename = os.path.join(image_dir, f"image_{i:04d}.jpg")
                import cv2
                cv2.imwrite(filename, frame)
                frame_count += 1
                print(f"Saved: {filename}")
                time.sleep(0.1)  # Small delay between captures
            else:
                break
        
        # Clean up
        tello.streamoff()
        print(f"\nTotal images downloaded: {frame_count}")
        print(f"Images saved to: {os.path.abspath(image_dir)}")
        
        return frame_count, image_dir
        
    except Exception as e:
        print(f"Error: {e}")
        return 0, None

def main():
    """Main function to download images from Tello"""
    print("=" * 50)
    print("Tello Drone Image Extraction Tool")
    print("Wings of Discovery")
    print("=" * 50)
    print()
    
    # Download images
    count, directory = download_images_from_tello()
    
    if count > 0:
        print(f"\n✓ Successfully downloaded {count} images!")
        print(f"Location: {directory}")
    else:
        print("\n✗ Failed to download images")

if __name__ == "__main__":
    main()
